### ISSUE TITLE
Crash on Android 6

### ISSUE THREAD

**Issue by DmBard** [eneim/kohii#23] opened 2019-06-26 11:23 UTC
I use lib version 1.0.0.2906-A09 and faced a crash on my OnePlus X device with Android Marshmallow:

`    java.lang.NoSuchMethodError: No virtual method remove(Ljava/lang/Object;Ljava/lang/Object;)Z in class Ljava/util/WeakHashMap; or its super classes (declaration of 'java.util.WeakHashMap' appears in /system/framework/core-libart.jar)
        at kohii.v1.PlaybackManager.onOwnerDestroy$kohii_release(PlaybackManager.kt:159)
        at kohii.v1.PlaybackManager_LifecycleAdapter.callMethods(PlaybackManager_LifecycleAdapter.java:43)
        at androidx.lifecycle.SingleGeneratedAdapterObserver.onStateChanged(SingleGeneratedAdapterObserver.java:29)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2845)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:947)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by eneim** [comment] 2019-06-27 14:35
@DmBard It was caused by a method only available in Java 8. I fixed it in other branch, will merge soon.

**Comment by eneim** [comment] 2019-06-28 01:50
@DmBard should be fixed in A10

**Closed by eneim** 2019-06-28 01:50 UTC
