### ISSUE TITLE
how to use Rebinder class in news version

### ISSUE THREAD

**Issue by yudikarma** [eneim/kohii#36] opened 2019-10-07 02:20 UTC
in your sample Class Rebinder have Renderer : Any like this ->
 `data class Rebinder<RENDERER : Any>(
  val tag: String,
  val rendererType: Class<RENDERER>
)`
but, in new release class Rebinder is already change like this ->
`data class Rebinder(
  val tag: String,
  val rendererType: Class<*>
)`
so that make me confuse to following your sample .

**Comment by eneim** [comment] 2019-10-07 08:57
@yudikarma which version you are using? In latest:

```
@Parcelize
data class Rebinder<RENDERER : Any>(
  val tag: String,
  val rendererType: Class<RENDERER>
) : Parcelable {
/// ....
}
```

FYI I know that this class is one with the worst design in current code base. When the main functions are stable I will revise it if I can. Or else I will document this class carefully.

**Comment by yudikarma** [comment] 2019-10-07 09:20
i try to modify your sample(echo fragment) add notifyitemchange on like btn click and video not re-play from start again. but, when i try in my project follow your sample, i got my video is re-play again from start. do you know why ?

**Comment by eneim** [comment] 2019-10-07 10:37
Do you set “tag” to your Video?

**Comment by yudikarma** [comment] 2019-10-07 10:57
this is my tag key ->

`val tagKey: String?
        get() = this.videoSources?.let { "${javaClass.canonicalName}::${it.imagepost?.get(0)?.video}::$adapterPosition" }`

this my setup in viewholdervideos -> 
`kohii.setUp(it.imagepost?.get(0)?.video?:"").with {
                tag = tagKey
                //preLoad = true
                repeatMode =Playable.REPEAT_MODE_ONE
                //callback = this@ViewHolderVideos
            }
                .bind(ViewTarget(mediaContainer)){playback ->

                    playback.addVolumeChangeListener(this@ViewHolderVideos)
                    if (viewmodel.volumeInfoStore.contains(this.adapterPosition)){
                        playback.volumeInfo = viewmodel.volumeInfoStore.get(this.adapterPosition)
                    }else{
                        viewmodel.saveVolumeInfo(this.adapterPosition,playback.volumeInfo) //save first
                    }
                    setupVolumeIcon(volumeInfo = playback.volumeInfo)
                    this@ViewHolderVideos.playback = playback
                    //listener.onItemLoaded(itemView,adapterPosition)
                }`

and setup hastableid ->
`init {
        setHasStableIds(true)
    }

    override fun getItemId(position: Int): Long {
        return position.toLong()
    }`

and this is setup kohii in fragment ->
`kohii = Kohii[this]
        rvHost = kohii.register(this).registerTargetHost(TargetHost.Builder(mview.feed_home))`

i think iam miss something, but i dot know where.

**Comment by eneim** [comment] 2019-10-07 12:36
@yudikarma So ``notifyitemchange`` works on my demo but not yours? How about you just change the media url (not other code) in your code? (Using same URL for all Videos should be Ok, just make the tags different).

**Comment by yudikarma** [comment] 2019-10-08 04:18
i cant do just change the media url (not other code) cause my structur not same with echo fragment, but iam already follow your sample echo fragment exacly, but i keep not get to video not re-play again on notifyitemchange. are iam missing some things ? my be for setup kohii

**Comment by eneim** [comment] 2019-10-08 12:23
@yudikarma I replace my code to use notifyitemchange and it still work fine. Can you share the code where you call ``notifyitemchange`` and if you override ``onBindViewHolder`` with the payloads please also include it.

**Comment by yudikarma** [comment] 2019-10-09 01:52
i create some gist how iam implement kohii at this [https://gist.github.com/yudikarma/c4b2de4614f1cd0b36bd93a86b5408c1](url) . notifyitemchange iam called after some action for like a post. and iam not use payload for that. just use interface.

**Comment by eneim** [comment] 2019-10-09 06:22
@yudikarma To ensure that the issue is not caused by a call to notifyItemChanged, can you try to put a button that once clicked, it just call ``notifyItemChanged`` on a specific position? This position can be a Video item, or non-Video item (to make sure a change to non-Video item affects Video or not).

**Comment by yudikarma** [comment] 2019-10-09 06:51
please check my demo [https://youtu.be/bnccgZL37GM](url).. i dot know why. i think it just iam missing something

**Comment by eneim** [comment] 2019-10-09 06:56
@yudikarma I think I figure it out ...

<img width="892" alt="Screen Shot 2019-10-09 at 15 54 43" src="https://user-images.githubusercontent.com/1776230/66458243-328f3a80-eaad-11e9-8b1c-83d6da17184d.png">

This is from ``ViewHolderVideos`` and it seems that you never update ``videoSources`` therefore tagKey is always null. You need a non-null tag to make it remember the Video. Please double check.

**Comment by yudikarma** [comment] 2019-10-09 07:07
wow :D amazinggg... work like a charm 👍 kohii is awesome library.. big thanks @eneim

**Comment by eneim** [comment] 2019-10-09 07:09
@yudikarma Ok sounds great. I will look at the screen on/off issue and may push some code later. Please close this issue. If you have other issue/trouble please create new one.

**Closed** 2019-10-09 07:14 UTC
